
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facerecognitionsystem;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author USER
 */
public class LecturerForm extends javax.swing.JFrame implements MouseListener, ActionListener {
    String url = "jdbc:mysql://localhost:3306/criminaldetection";
    String user = "root";
    String Password = "";
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form LecturerForm
     */
    public LecturerForm() {
        initComponents();
        showTableData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        txtDpt = new javax.swing.JTextField();
        txtFac = new javax.swing.JTextField();
        txtCrs = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        LecReport = new javax.swing.JButton();
        PhotoFunc = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lecturer Form");

        jLabel1.setText("Last Name");

        jLabel2.setText("Middle Name");

        jLabel3.setText("First Name");

        jLabel4.setText("Department");

        jLabel5.setText("Faculty");

        jLabel6.setText("Course(s)");

        jLabel7.setText("Phone No");

        jLabel8.setText("E-Mail");

        txtLname.setName("txtLname"); // NOI18N
        txtLname.addActionListener(this);

        txtMname.setName("txtMname"); // NOI18N

        txtFname.setName("txtFname"); // NOI18N

        txtAdd.setColumns(20);
        txtAdd.setRows(5);
        txtAdd.setName("txtAdd"); // NOI18N
        jScrollPane1.setViewportView(txtAdd);

        txtDpt.setName(""); // NOI18N

        txtFac.setName("txtFac"); // NOI18N

        txtCrs.setName("txtCrs"); // NOI18N

        txtPhone.setName("txtPhone"); // NOI18N

        txtMail.setName("txtMail"); // NOI18N

        jLabel9.setText("Address");

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add New");
        jButton1.addActionListener(this);

        jButton2.setBackground(new java.awt.Color(102, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addMouseListener(this);
        jButton2.addActionListener(this);

        jButton3.setBackground(new java.awt.Color(255, 0, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(this);

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setText("MAIN MENU");
        jButton4.addMouseListener(this);
        jButton4.addActionListener(this);

        jLabel10.setText("Marital Status");

        txtStatus.setName("txtStatus"); // NOI18N

        jButton5.setText("Photo");
        jButton5.addActionListener(this);

        jLabel11.setText("Id");

        jButton6.setText("GO");
        jButton6.addActionListener(this);

        jButton7.setBackground(new java.awt.Color(153, 102, 255));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(this);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tboysure\\Desktop\\OJO JOHN TAIWO(2010245020178)\\FaceRecognitionSystem\\Images\\ibpoly.png")); // NOI18N
        jLabel12.setText("jLabel12");

        LecReport.setText("Report");
        LecReport.addActionListener(this);

        PhotoFunc.setBackground(new java.awt.Color(51, 204, 0));
        PhotoFunc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PhotoFunc.setText("Detect Face");
        PhotoFunc.addActionListener(this);

        jLabel13.setText("Path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLname)
                                        .addComponent(txtMname)
                                        .addComponent(txtFname)
                                        .addComponent(txtDpt, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton6))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtFac)
                                        .addComponent(txtCrs)
                                        .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(PhotoFunc))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(LecReport)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addComponent(PhotoFunc, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LecReport)
                        .addGap(158, 158, 158)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtDpt.getAccessibleContext().setAccessibleName("txtDpt");

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == txtLname) {
            LecturerForm.this.txtLnameActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            LecturerForm.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            LecturerForm.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            LecturerForm.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            LecturerForm.this.jButton4ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton5) {
            LecturerForm.this.jButton5ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton6) {
            LecturerForm.this.jButton6ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton7) {
            LecturerForm.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == LecReport) {
            LecturerForm.this.LecReportActionPerformed(evt);
        }
        else if (evt.getSource() == PhotoFunc) {
            LecturerForm.this.PhotoFuncActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jButton2) {
            LecturerForm.this.jButton2MouseClicked(evt);
        }
        else if (evt.getSource() == jButton4) {
            LecturerForm.this.jButton4MouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuForm().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException ex1){
            JOptionPane.showMessageDialog(null, ex1.getMessage()); 
        
        }
        
        try{
            String query;
            query = "INSERT INTO `lecturerinfo`(`LastName`, `MiddleName`, `FirstName`, `Dept`, `Faculty`, `Course(s)`, `phoneNo`, `Email`, `Marital`, `Address`, `Photo`, `Path`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection(url, user, Password);
            pst = conn.prepareStatement(query);
            pst.setString(1,txtLname.getText());
            pst.setString(2,txtMname.getText());
            pst.setString(3,txtFname.getText());
            pst.setString(4,txtDpt.getText());
            pst.setString(5,txtFac.getText());
            pst.setString(6,txtCrs.getText());
            pst.setString(7,txtPhone.getText());
            pst.setString(8,txtMail.getText());
            pst.setString(9,txtStatus.getText());
            pst.setString(10,txtAdd.getText());
            pst.setBytes(11, Photo);
            pst.setString(12, txtPath.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registered Successfully");
            
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex);
        }  
        showTableData();
    }//GEN-LAST:event_jButton2MouseClicked

    public void showTableData() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            String sql = "SELECT * FROM `lecturerinfo`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         txtId.setText("");
        txtLname.setText("");
         txtMname.setText("");
         txtFname.setText("");
         txtDpt.setText("");
         txtFac.setText("");
         txtCrs.setText("");
        txtPhone.setText("");
        txtStatus.setText("");
        txtMail.setText("");
        txtAdd.setText("");
        lblImg.setIcon(null);
        txtPath.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException ex1){
            JOptionPane.showMessageDialog(null, ex1.getMessage());  
    }//GEN-LAST:event_jButton3ActionPerformed
   
        
        try{
            String query;
            query = "DELETE FROM  `lecturerinfo` WHERE Id = ?";//(`LastName`, `MiddleName`, `FirstName`, `Dept`, `Faculty`, `Course(s)`, `phoneNo`, `Email`, `Marital`, `Address`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection(url, user, Password);
            pst = conn.prepareStatement(query);
            pst.setString(1, txtId.getText());
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
             txtId.setText("");
        txtLname.setText("");
         txtMname.setText("");
         txtFname.setText("");
         txtDpt.setText("");
         txtFac.setText("");
         txtCrs.setText("");
        txtPhone.setText("");
        txtStatus.setText("");
        txtMail.setText("");
        txtAdd.setText("");
        lblImg.setIcon(null);
        txtPath.setText("");
        }catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,ex);
        }
        showTableData();
    }
     
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" *Images", "gif", "jpg", "png");
        File f = chooser.getSelectedFile();
        filename  = f.getAbsolutePath();
        lblImg.setIcon(new ImageIcon(f.toString()));
        txtPath.setText(filename);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream  bos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum = fis.read(buff))!=-1;){
                bos.write(buff, 0, readNum);
            
            }
            Photo = bos.toByteArray();
           
           
        }catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e);
                    } 
        
        
        
        
        
        /**
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(icon);
        ***/
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

       Function f = new Function();
        ResultSet rs = null;
        PreparedStatement pst = null;
        String Id = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String g = "Gender";
        String dpt = "Department";
        String fc = "Faculty";
        String crs = "Course(s)";
        String st = "Marital";
        String p = "PhoneNo";
        String m = "mail";
        String a = "Address";
        String im = "Images";
        String ph  = "Photo";
        String pt = "Path";

        rs = f.find(txtId.getText());
        //rs = f.find(txtSearch.getText());
        try {
                byte[] imageByte;
                Image image;
            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtDpt.setText(rs.getString("Dept"));
               txtFac.setText(rs.getString("Faculty"));
                txtCrs.setText(rs.getString("Course(s)"));
                txtPhone.setText(rs.getString("PhoneNo"));
                txtMail.setText(rs.getString("Email"));
                txtAdd.setText(rs.getString("Address"));
                txtStatus.setText(rs.getString("Marital"));
    
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
                txtPath.setText(rs.getString("Path"));
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput Id Into Id Field and try Again. ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

       
    }//GEN-LAST:event_jButton6ActionPerformed
  public class Function {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM `lecturerinfo`WHERE  Id = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
    }                                     

     }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     try{
         Class.forName("com.mysql.jdbc.Driver");
     }catch(Exception ex)
     {
         JOptionPane.showMessageDialog(null,ex);
     }
      try
      {
          String sql = "UPDATE `lecturerinfo` SET `LastName`=?,`MiddleName`=?,`FirstName`=?,`Dept`=?,`Faculty`=?,`Course(s)`=?,`phoneNo`=?,`Email`=?,`Marital`=?,`Address`=?,`Photo`=?, `Path`=? WHERE Id=?";
           conn = DriverManager.getConnection(url, user, Password);
            pst = conn.prepareStatement(sql);
             pst.setString(12,txtId.getText());
            pst.setString(1,txtLname.getText());
            pst.setString(2,txtMname.getText());
            pst.setString(3,txtFname.getText());
            pst.setString(4,txtDpt.getText());
            pst.setString(5,txtFac.getText());
            pst.setString(6,txtCrs.getText());
            pst.setString(7,txtPhone.getText());
            pst.setString(8,txtMail.getText());
            pst.setString(9,txtStatus.getText());
            pst.setString(10,txtAdd.getText());
             pst.setBytes(11, Photo);
             pst.setString(12,txtPath.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
      }catch(Exception ex)
      {
          JOptionPane.showMessageDialog(null,ex);
      }
      showTableData();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void LecReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecReportActionPerformed
       try{
           InputStream in = new FileInputStream(new File("C:\\Users\\USER\\Desktop\\Face Recognition System\\FaceRecognitionSystem\\src\\reports\\LecturerReport.jrxml"));
           JasperDesign jd = JRXmlLoader.load(in);
           String sql = "Select * From lecturerinfo";
           JRDesignQuery newQuery = new JRDesignQuery();
           newQuery.setText(sql);
           jd.setQuery(newQuery);
           JasperReport jr = JasperCompileManager.compileReport(jd);
           HashMap para = new HashMap();
           JasperPrint j = JasperFillManager.fillReport(jr,para,conn);
           JasperViewer.viewReport(j,false);
           OutputStream os = new FileOutputStream(new File("C\\reports"));
           JasperExportManager.exportReportToPdfStream(j,os);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_LecReportActionPerformed

    private void PhotoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoFuncActionPerformed
       
       PhotFunction f = new PhotFunction();
        ResultSet rs = null;
        PreparedStatement pst = null;
        String Id = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String g = "Gender";
        String dpt = "Department";
        String fc = "Faculty";
        String crs = "Course(s)";
        String st = "Marital";
        String p = "PhoneNo";
        String m = "mail";
        String a = "Address";
        String im = "Images";
        String ph  = "Photo";

        rs = f.find(txtPath.getText());
        //rs = f.find(txtSearch.getText());
        try {
                byte[] imageByte;
                Image image;
            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtDpt.setText(rs.getString("Dept"));
               txtFac.setText(rs.getString("Faculty"));
                txtCrs.setText(rs.getString("Course(s)"));
                txtPhone.setText(rs.getString("PhoneNo"));
                txtMail.setText(rs.getString("Email"));
                txtAdd.setText(rs.getString("Address"));
                txtStatus.setText(rs.getString("Marital"));
    
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput Another Photo and try Again! ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_PhotoFuncActionPerformed
 
    public class PhotFunction {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM `lecturerinfo`WHERE Path = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
    }                                     

     }
   
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton LecReport;
    javax.swing.JButton PhotoFunc;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JButton jButton5;
    javax.swing.JButton jButton6;
    javax.swing.JButton jButton7;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable1;
    javax.swing.JLabel lblImg;
    javax.swing.JTextArea txtAdd;
    javax.swing.JTextField txtCrs;
    javax.swing.JTextField txtDpt;
    javax.swing.JTextField txtFac;
    javax.swing.JTextField txtFname;
    javax.swing.JTextField txtId;
    javax.swing.JTextField txtLname;
    javax.swing.JTextField txtMail;
    javax.swing.JTextField txtMname;
    javax.swing.JTextField txtPath;
    javax.swing.JTextField txtPhone;
    javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    byte [] Photo = null;
    String filename = null;
            
    private PreparedStatement setString(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
