/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facerecognitionsystem;
import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class LoginForm extends javax.swing.JFrame implements MouseListener, ActionListener {
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Login");
        jButton1.addMouseListener(this);
        jButton1.addActionListener(this);
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 370, 80, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setText("BACK");
        jButton2.addMouseListener(this);
        jButton2.addActionListener(this);
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 370, 70, 30);

        jTextField1.addActionListener(this);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 320, 249, 22);

        jPasswordField1.addActionListener(this);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(350, 350, 250, 22);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(961, 0, 0, 317);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tboysure\\Desktop\\OJO JOHN TAIWO(2010245020178)\\FaceRecognitionSystem\\Images\\Login.PNG")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 610, 410);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(967, 0, 590, 440);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            LoginForm.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            LoginForm.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jTextField1) {
            LoginForm.this.jTextField1ActionPerformed(evt);
        }
        else if (evt.getSource() == jPasswordField1) {
            LoginForm.this.jPasswordField1ActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jButton1) {
            LoginForm.this.jButton1MouseClicked(evt);
        }
        else if (evt.getSource() == jButton2) {
            LoginForm.this.jButton2MouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     String ext = new String(jPasswordField1.getPassword());
  /**    
 if(jTextField1.getText().equals("Tboysure") && ext.equals("taiwos"))
       {
           JOptionPane.showMessageDialog(null, "Login Successfully");
           this.dispose();
           new LoginMenu().setVisible(true);
       }
       **/
       if((jTextField1.getText().equals("admin") && ext.equals("admin")))
       {
           JOptionPane.showMessageDialog(null, "Login Successfully as an Admin".toUpperCase(Locale.ITALY));
           this.dispose();
           new MenuForm().setVisible(true);
       }
       else if((jTextField1.getText().equals("student") && ext.equals("polyibadan")))
       {
           JOptionPane.showMessageDialog(null, "Login Successfully as a \nStudent".toUpperCase(Locale.ITALY));
           this.dispose();
         try {
             new Student_Info().setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
         }
       }
       else if((jTextField1.getText().equals("lecturer") && ext.equals("polyibadan")))
       {
           JOptionPane.showMessageDialog(null, "Login Successfully as a \nLecturer".toUpperCase(Locale.ITALY));
           this.dispose();
           new LecturerForm().setVisible(true);
       }
       else if((jTextField1.getText().equals("security") && ext.equals("polyibadan")))
       {
           JOptionPane.showMessageDialog(null, "Login Successfully as a \nSecurity Officer".toUpperCase(Locale.ITALY));
           this.dispose();
           new SecurityForm().setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null,"Login Denied!");
           //jTextField1.getText().equals(" ");
           //jPasswordField1.getPassword().equals(" ");
           jTextField1.setText(" ");
           jPasswordField1.setText("");
            
    }//GEN-LAST:event_jButton1MouseClicked
          
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
      new LoginMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JLabel jLabel3;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPasswordField jPasswordField1;
    javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
