/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facerecognitionsystem;

import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class SecurityForm extends javax.swing.JFrame implements MouseListener, ActionListener {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String url = "jdbc:mysql://localhost:3306/criminaldetection";
    String user = "root";
    String Password = "";

    ;
    public SecurityForm() {
        initComponents();
        showTableData();

    }
    //String txtImg = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        txtLname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtPost = new javax.swing.JTextField();
        txtGur = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Id = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        tblHide = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        lblUpload = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        photoFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Security Form");

        jLabel1.setText("Last Name");

        jLabel2.setText("Middle Name");

        jLabel3.setText("First Name");

        jLabel4.setText("Gender");

        jLabel5.setText("Post");

        jLabel6.setText("Guarantor");

        jLabel7.setText("Phone No");

        jLabel8.setText("E-Mail");

        jLabel9.setText("Address");

        txtAdd.setColumns(20);
        txtAdd.setRows(5);
        jScrollPane1.setViewportView(txtAdd);

        txtLname.setName("lname"); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("AddNew");
        jButton1.addActionListener(this);

        btnSubmit.setBackground(new java.awt.Color(51, 0, 204));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this);

        btnDelete.setBackground(new java.awt.Color(255, 0, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this);

        jButton4.setBackground(new java.awt.Color(102, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("MAIN MENU");
        jButton4.addMouseListener(this);
        jButton4.addActionListener(this);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Id.setText("    Id");

        tblHide.setText("HIDE TABLE");
        tblHide.addActionListener(this);

        btnGo.setText("GO");
        btnGo.addActionListener(this);

        lblUpload.setText("Upload");
        lblUpload.addActionListener(this);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tboysure\\Desktop\\OJO JOHN TAIWO(2010245020178)\\FaceRecognitionSystem\\Images\\IB-Poly.jpeg")); // NOI18N
        jLabel10.setText("jLabel10");

        jButton2.setBackground(new java.awt.Color(153, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(this);

        Report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Report.setText("Report");
        Report.addActionListener(this);

        photoFunc.setBackground(new java.awt.Color(51, 204, 0));
        photoFunc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        photoFunc.setText("Detect Face");
        photoFunc.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtGur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnGo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUpload))
                                    .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(Report)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(photoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(tblHide)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Id)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUpload))
                                .addGap(1, 1, 1))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Report)
                        .addGap(28, 28, 28)))
                .addComponent(tblHide)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            SecurityForm.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == btnSubmit) {
            SecurityForm.this.btnSubmitActionPerformed(evt);
        }
        else if (evt.getSource() == btnDelete) {
            SecurityForm.this.btnDeleteActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            SecurityForm.this.jButton4ActionPerformed(evt);
        }
        else if (evt.getSource() == tblHide) {
            SecurityForm.this.tblHideActionPerformed(evt);
        }
        else if (evt.getSource() == btnGo) {
            SecurityForm.this.btnGoActionPerformed(evt);
        }
        else if (evt.getSource() == lblUpload) {
            SecurityForm.this.lblUploadActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            SecurityForm.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == Report) {
            SecurityForm.this.ReportActionPerformed(evt);
        }
        else if (evt.getSource() == photoFunc) {
            SecurityForm.this.photoFuncActionPerformed(evt);
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == jButton4) {
            SecurityForm.this.jButton4MouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents
/**
    public ImageIcon ResizeImage(String txtImg1, byte[] pics) {
        ImageIcon myImage = null;
        if (txtImg1 != null) {
            myImage = new ImageIcon(txtImg1);
        } else {
            myImage = new ImageIcon(pics);
        }
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
//08029087155      
    }
**/
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuForm().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        txtId.setText("");
        txtLname.setText("");
        txtMname.setText("");
        txtFname.setText("");
        txtGender.setText("");
        txtPost.setText("");
        txtGur.setText("");
        txtPhone.setText("");
        txtMail.setText("");
        txtAdd.setText("");
        txtPath.setText("");
        lblImg.setIcon(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Boolean validation = false;
        if (txtLname.getText().trim().isEmpty() || txtMname.getText().trim().isEmpty() || txtFname.getText().trim().isEmpty() || txtGender.getText().trim().isEmpty() || txtPost.getText().trim().isEmpty() || txtGur.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill in All the Tex box", "Error!", JOptionPane.ERROR_MESSAGE);
            validation = false;
        } else {
            validation = true;
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        try {
            /**
             * byte [] img = rs.getBytes("Image"); ImageIcon img1 = new
             * ImageIcon(Image); Image im1 = img.getImage(im1); Image myImage;
             * myImage = img1.getImage().getScaledInstance(lblImg.getWidth(),
             * lblImg.getHeight(), Image.SCALE_SMOOTH); ImageIcon Image= new
             * ImageIcon(myImage); lblImg.setIcon(img1);
                 *
             */

            String query = "INSERT INTO `security`(`Id`, `LastName`, `MiddleName`, `FirstName`, `Gender`, `Post`, `Garantor`, `Phone`, `Email`, `Address`, `Path`, `Photo`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            //conn = DriverManager.getConnection("jdbc:mysql://localhost/criminaldetection","root","");
            pst = conn.prepareStatement(query);
            pst.setString(1, txtId.getText());
            pst.setString(2, txtLname.getText());
            pst.setString(3, txtMname.getText());
            pst.setString(4, txtFname.getText());
            pst.setString(5, txtGender.getText());
            pst.setString(6, txtPost.getText());
            pst.setString(7, txtGur.getText());
            pst.setString(8, txtPhone.getText());
            pst.setString(9, txtMail.getText());
            pst.setString(10, txtAdd.getText());
            pst.setString(11, txtPath.getText());
            pst.setBytes(12, Photo);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registered Successfully");

    }//GEN-LAST:event_btnSubmitActionPerformed
catch (HeadlessException | SQLException ex1) {
            JOptionPane.showMessageDialog(null, ex1);
        }
        showTableData();
    }

    public void showTableData() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            String sql = "SELECT * FROM `security`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        try {

            String query = "DELETE FROM `security` WHERE Id = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            //conn = DriverManager.getConnection("jdbc:mysql://localhost/criminaldetection","root","");
            pst = conn.prepareStatement(query);
            pst.setString(1, txtId.getText());
            pst.executeUpdate();

           
            JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully");

        } catch (HeadlessException | SQLException ex1) {
            JOptionPane.showMessageDialog(null, ex1);
        }
         txtId.setText("");
            txtLname.setText("");
            txtMname.setText("");
            txtFname.setText("");
            txtGender.setText("");
            txtPost.setText("");
            txtGur.setText("");
            txtPhone.setText("");
            txtMail.setText("");
            txtAdd.setText("");
            txtPath.setText("");
            lblImg.setIcon(null);
        showTableData();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHideActionPerformed

        jTable1.disable();
    }//GEN-LAST:event_tblHideActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        //txtSearch = txtId;

        Function f = new Function();
        ResultSet rs = null;
        PreparedStatement pst = null;
        String search = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String g = "Gender";
        String ga = "Garantor";
        String ps = "Post";
        String p = "Phone";
        String m = "mail";
        String a = "Address";
        String path = "Path";
        String ph  = "Photo";
        //ImageIcon icon = new ImageIcon(filename);

        rs = f.find(txtId.getText());
        //rs = f.find(txtSearch.getText());
        try {
            byte[] imageByte;
            Image image;
            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtGender.setText(rs.getString("Gender"));
                txtPost.setText(rs.getString("Post"));
                txtGur.setText(rs.getString("Garantor"));
                txtPhone.setText(rs.getString("Phone"));
                txtMail.setText(rs.getString("Email"));
                txtAdd.setText(rs.getString("Address"));
                txtPath.setText(rs.getString("Path"));
                
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
                
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput Id Into Id Field and try Again. ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    public class Function {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM security WHERE Id = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
    }//GEN-LAST:event_btnGoActionPerformed
    }

    private void lblUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblUploadActionPerformed
 /**    
       // My First Code to add and Save Images into the database.
        JFileChooser chooser = new JFileChooser();
          chooser.showOpenDialog(null); File f = chooser.getSelectedFile();
          String filename = f.getAbsolutePath(); txtImg.setText(filename);
          Image getAbsoluthPath = null; ImageIcon icon = new
          ImageIcon(filename); 
          Image image = icon.getImage().getScaledInstance(lblImg.getWidth(),
         lblImg.getHeight(), Image.SCALE_SMOOTH); 
         lblImg.setIcon(icon);
        
       **/
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" *Images", "gif", "jpg", "png");
        filename  = f.getAbsolutePath();
        lblImg.setIcon(new ImageIcon(f.toString()));
        txtPath.setText(filename);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream  bos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum = fis.read(buff))!=-1;){
                bos.write(buff, 0, readNum);
            
            }
            Photo = bos.toByteArray();
           
           
        }catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e);
                    }
        
        
        /**
        // FileNameExtensionFilter filter = new FileNameExtensionFilter(" *Images", "gif", "jpg", "png");
       // file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();

            String path = selectedFile.getAbsolutePath();
            lblImg.setIcon(ResizeImage(path, null));
            txtImg = path;
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No Image Selected");
        }
        

        **/
          
        

    }//GEN-LAST:event_lblUploadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }       
         try{
             String  query ="UPDATE `security` SET LastName=?, MiddleName=?,FirstName=?, Gender=?, Post=?, Garantor=?, Phone=?, Email=?, Address=?, Path=?, Photo=? WHERE Id=?";
           // String  query = "UPDATE `security` SET LastName='"+txtLname.getText()+"', MiddleName='"+txtMname.getText()+"', FirstName ='"+txtFname.getText()+"', Gender='"+txtGender.getText()+"', Post ='"+txtPost.getText()+"', Garantor='"+txtGur.getText()+"', Phone='"+txtPhone.getText()+"', Email='"+txtMail.getText()+"', Address ='"+txtAdd.getText()+"', Path ='"+txtImg.getText()+"', WHERE Id="+txtId.getText();
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            pst = conn.prepareStatement(query);
            
            pst.setString(12, txtId.getText());
            pst.setString(1, txtLname.getText());
            pst.setString(2, txtMname.getText());
            pst.setString(3, txtFname.getText());
            pst.setString(4, txtGender.getText());
            pst.setString(5, txtPost.getText());
            pst.setString(6, txtGur.getText());
            pst.setString(7, txtPhone.getText());
            pst.setString(8, txtMail.getText());
            pst.setString(9, txtAdd.getText());
            pst.setString(10, txtPath.getText());
            pst.setBytes(11, Photo);
            
             pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Updated Successfully");

    }                                         
catch (HeadlessException | SQLException ex1) {
            JOptionPane.showMessageDialog(null, ex1);
        }
       
         showTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        try{
           InputStream in = new FileInputStream(new File("C:\\Users\\USER\\Desktop\\Face Recognition System\\FaceRecognitionSystem\\src\\SecurityReport.jrxml"));
           JasperDesign jd = JRXmlLoader.load(in);
           String sql = "Select * From security";
           JRDesignQuery newQuery = new JRDesignQuery();
           newQuery.setText(sql);
           jd.setQuery(newQuery);
           JasperReport jr = JasperCompileManager.compileReport(jd);
           HashMap para = new HashMap();
           JasperPrint j = JasperFillManager.fillReport(jr,para,conn);
           JasperViewer.viewReport(j,false);
           OutputStream os = new FileOutputStream(new File("D\\reports"));
           JasperExportManager.exportReportToPdfStream(j,os);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_ReportActionPerformed

    private void photoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoFuncActionPerformed
        
        PhFunction f = new PhFunction();
        ResultSet rs = null;
        PreparedStatement pst = null;
        String search = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String g = "Gender";
        String ga = "Garantor";
        String ps = "Post";
        String p = "Phone";
        String m = "mail";
        String a = "Address";
        String path = "Path";
        String ph  = "Photo";
        //ImageIcon icon = new ImageIcon(filename);

        rs = f.find(txtPath.getText());
        //rs = f.find(txtSearch.getText());
        try {
            byte[] imageByte;
            Image image;
            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtGender.setText(rs.getString("Gender"));
                txtPost.setText(rs.getString("Post"));
                txtGur.setText(rs.getString("Garantor"));
                txtPhone.setText(rs.getString("Phone"));
                txtMail.setText(rs.getString("Email"));
                txtAdd.setText(rs.getString("Address"));
                txtPath.setText(rs.getString("Path"));
                
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
                
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput anoder Photo and try Again. ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_photoFuncActionPerformed
public class PhFunction {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM security WHERE Path = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
    }  
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SecurityForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel Id;
    javax.swing.JButton Report;
    javax.swing.JButton btnDelete;
    javax.swing.JButton btnGo;
    javax.swing.JButton btnSubmit;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton4;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable1;
    javax.swing.JLabel lblImg;
    javax.swing.JButton lblUpload;
    javax.swing.JButton photoFunc;
    javax.swing.JButton tblHide;
    javax.swing.JTextArea txtAdd;
    javax.swing.JTextField txtFname;
    javax.swing.JTextField txtGender;
    javax.swing.JTextField txtGur;
    javax.swing.JTextField txtId;
    javax.swing.JTextField txtLname;
    javax.swing.JTextField txtMail;
    javax.swing.JTextField txtMname;
    javax.swing.JTextField txtPath;
    javax.swing.JTextField txtPhone;
    javax.swing.JTextField txtPost;
    // End of variables declaration//GEN-END:variables

    String filename = null;
    int s=0;
    int Num;
    byte[] Photo = null;
    private PreparedStatement setString(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
