/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facerecognitionsystem;

import java.awt.HeadlessException;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import net.proteanit.sql.DbUtils;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import static java.nio.file.Files.size;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.Icon;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.opencv.photo.Photo;

/**
 *
 * @author USER
 */
public class Student_Info extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/criminaldetection";
    String user = "root";
    String Password = "";
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Student_Info
     * @throws java.sql.SQLException
     */
    public Student_Info() throws SQLException {
        initComponents();
        showTableData();
        conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
        Toolkit toolkit = getToolkit();
        //setLocation(size.width / 2 - getWidth() / 2,
         //       size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDpt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFac = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrgm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        btnAddNew = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        btnImg = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        PhotoFun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT INFO");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel1.setText("STUDENT REGISTRATION FORM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("THE POLYTECHNICH IBADAN");

        jLabel4.setText("STUDENT ID");
        jScrollPane1.setViewportView(jLabel4);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel3.setText("LAST NAME");

        jLabel5.setText("MIDDLE NAME");

        jLabel6.setText("FIRST NAME");

        jLabel7.setText("DOB");

        txtDOB.setText("DD/MM/YY");

        jLabel8.setText("STATUS");

        jLabel9.setText("COURSE");

        jLabel10.setText("DEPARTMENT");

        jLabel11.setText("FACULTY");

        jLabel12.setText("PROGRAM");

        jLabel13.setText("LEVEL");

        jLabel14.setText("PHONE NO");

        jLabel15.setText("E-MAIL");

        jLabel16.setText("ADDRESS");

        txtAdd.setColumns(20);
        txtAdd.setRows(5);
        jScrollPane2.setViewportView(txtAdd);

        btnAddNew.setBackground(new java.awt.Color(102, 255, 0));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNew.setText("NEW");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(102, 0, 204));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });

        btnImg.setText("Upload");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(153, 51, 0));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu.setText("Logout");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel17.setText("Path");

        jLabel18.setText("jLabel18");

        jLabel19.setText("jLabel18");

        jLabel20.setText("jLabel18");

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 153));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(153, 102, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Menu.setBackground(new java.awt.Color(102, 0, 51));
        Menu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Menu.setText("MENU");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        PhotoFun.setBackground(new java.awt.Color(51, 204, 0));
        PhotoFun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PhotoFun.setText("Detect Face");
        PhotoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoFunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOB)
                            .addComponent(txtStatus)
                            .addComponent(txtCourse)
                            .addComponent(txtDpt)
                            .addComponent(txtMname)
                            .addComponent(txtFname)
                            .addComponent(txtFac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrgm))
                                .addGap(45, 45, 45)
                                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(424, 424, 424))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnImg))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addComponent(PhotoFun))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(420, 420, 420))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSubmit)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(562, 562, 562)
                                .addComponent(btnMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrgm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDpt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImg))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(PhotoFun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnSubmit)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(Menu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        txtId.setText("");
        txtLname.setText("");
        txtMname.setText("");
        txtFname.setText("");
        txtDpt.setText("");
        txtFac.setText("");
        txtAdd.setText("");
        txtDOB.setText("");
        txtPrgm.setText("");
        txtStatus.setText("");
        txtPhone.setText("");
        txtLevel.setText("");
        txtCourse.setText("");
        txtMail.setText("");
        txtAdd.setText("");
        txtPath.setText("");
        lblImg.setIcon(null);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex1) {
            JOptionPane.showMessageDialog(null, ex1.getMessage());

        }

        try {
            String query;
            query = "INSERT INTO `student_info`(`Id`, `LastName`, `MiddleName`, `FirstName`, `DOB`, `Status`, `Course`, `Department`, `Faculty`, `Program`, `Level`, `Phone`, `Email`, `Address`, `Path`, `Photo`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            conn = java.sql.DriverManager.getConnection(url, user, Password);

            pst = conn.prepareStatement(query);
            pst.setString(1, txtId.getText());
            pst.setString(2, txtLname.getText());
            pst.setString(3, txtMname.getText());
            pst.setString(4, txtFname.getText());
            pst.setString(5, txtDOB.getText());
            pst.setString(6, txtStatus.getText());
            pst.setString(7, txtCourse.getText());
            pst.setString(8, txtDpt.getText());
            pst.setString(9, txtFac.getText());
            pst.setString(10, txtPrgm.getText());
            pst.setString(11, txtLevel.getText());
            pst.setString(12, txtPhone.getText());
            pst.setString(13, txtMail.getText());
            pst.setString(14, txtAdd.getText());
            pst.setString(15, txtPath.getText());
            pst.setBytes(16, Photo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration is Successful");

        } catch (HeadlessException | SQLException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
         showTableData();
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    public void showTableData() {
        try {
            conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            String sql = "SELECT * FROM `Student_Info`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        /**
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txtImg.setText(filename);
        Image getAbsoluthPath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(icon);
        txtImg.setText(filename);
        **/
        
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" *Images", "gif", "jpg", "png");
        filename  = f.getAbsolutePath();
       lblImg.setIcon(new ImageIcon(f.toString()));
        txtPath.setText(filename);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream  bos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum = fis.read(buff))!=-1;){
                bos.write(buff, 0, readNum);
            
            }
            Photo = bos.toByteArray();
           
           
        }catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e);
                    }
    }//GEN-LAST:event_btnImgActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new LoginMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Function f = new Function();
        ResultSet rs = null;
        //PreparedStatement pst = null;
        String Id = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String cs = "Course";
        String dp = "Depatment";
        String lv = "Level";
        String pg = "Program";
        String pn = "Phone";
        String m = "mail";
        String a = "Address";
        String db = "DOB";
        String pt = "Path";
        String st = "Status";
        String fc = "Faculty";
        String ph = "Photo";
        

       
        rs = f.find(txtId.getText());
        //rs = f.find(txtSearch.getText());
        try {
              byte[] imageByte;
                Image image;

            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtDOB.setText(rs.getString("DOB"));
                txtLevel.setText(rs.getString("Level"));
                txtPhone.setText(rs.getString("Phone"));
                txtMail.setText(rs.getString("Email"));
                txtStatus.setText(rs.getString("Status"));
                txtCourse.setText(rs.getString("Course"));
                txtDpt.setText(rs.getString("Department"));
                txtFac.setText(rs.getString("Faculty"));
                txtPrgm.setText(rs.getString("Program"));
                txtAdd.setText(rs.getString("Address"));
                txtPath.setText(rs.getString("Path"));
               // pst.setBytes(12, Photo);
                
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
         
    /*           
       File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        //ImageIcon icon = new ImageIcon(filename);
        txtImg.setText(rs.getString("Image"));
         txtImg.setText(filename);
              if(txtImg.setText==filename)
                      {
                           lblImg.setIcon(icon);
                      }
              else{
                  JOptionPane.showMessageDialog(null, "NO DATA FOUND");
              }
                     //File f = chooser.getSelectedFile();
        
       
         String filename = f.getAbsolutePath();
        txtImg.setText(filename);
        Image getAbsoluthPath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(icon);
        txtImg.setText(filename);
        
                  String filename = null;
                 //txtImg.setText(filename);
                  Image getAbsoluthPath = null;
                 byte [] img = rs.getBytes("Images");
                Icon filename;
                 ImageIcon img1 = new ImageIcon((Image) filename);
                 Image im1 = img.getImage(filename);
                 Image myImage;
                myImage = img1.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
                 ImageIcon Image= new ImageIcon(myImage);
                 lblImg.setIcon(filename);
                  */ 
       
       
       
                //ImageIcon icon = new ImageIcon(filename);
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput Id Into Id Field and try Again. ");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public class Function {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM `student_info` WHERE Id = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         try{
           InputStream ins = new FileInputStream(new File("C:\\Users\\USER\\Desktop\\Face Recognition System\\FaceRecognitionSystem\\src\\reports\\StudentReport.jrxml"));
           JasperDesign jdn = JRXmlLoader.load(ins);
           String sql = "SELECT * FROM student_info";
           JRDesignQuery newQuery1 = new JRDesignQuery();
           newQuery1.setText(sql);
           jdn.setQuery(newQuery1);
           JasperReport jr1 = JasperCompileManager.compileReport(jdn);
           HashMap para1 = new HashMap();
           JasperPrint jp = JasperFillManager.fillReport(jr1,para1,conn);
           JasperViewer.viewReport(jp,false);
           OutputStream os = new FileOutputStream(new File("D\\reports"));
           JasperExportManager.exportReportToPdfStream(jp,os);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null,ex);
       }
        /**
        String value = txtId.getText();
        String value0 = txtLname.getText();
        String value1 = txtMname.getText();
        String value2 = txtFname.getText();
        String value3 = txtDOB.getText();
        String value4 = txtStatus.getText();
        String value5 = txtCourse.getText();
        String value6 = txtDpt.getText();
        String value7 = txtFac.getText();
        String value8 = txtPrgm.getText();
        String value9 = txtLevel.getText();
        String value10 = txtPhone.getText();
        String value11 = txtMail.getText();
        String value12 = txtAdd.getText();
        //String value13 = lblImg.SetIcon(icon);  

        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(value + " " + value0 + " " + value1 + " " + value2 + " " + value3 + " " + value4 + " " + value5 + " " + value6 + " " + value7 + " " + value8 + " " + value9 + " " + value10 + " " + value11 + " " + value12 + " STUDENT SLIP " + " .pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filepath = dialog.getSelectedFile().getParent();
            System.out.println("Printed successfully");
            
            }
            **/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased

    }//GEN-LAST:event_jButton3KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        try{
            conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
            String sql = "DELETE FROM `student_info` WHERE Id=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
          txtId.setText("");
        txtLname.setText("");
        txtMname.setText("");
        txtFname.setText("");
        txtDpt.setText("");
        txtFac.setText("");
        txtAdd.setText("");
        txtDOB.setText("");
        txtPrgm.setText("");
        txtStatus.setText("");
        txtPhone.setText("");
        txtLevel.setText("");
        txtCourse.setText("");
        txtMail.setText("");
        txtAdd.setText("");
        txtPath.setText("");
        lblImg.setIcon(null);
        
          showTableData();
        //if(txtId.setText=="" and )
          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
        
        try{
             conn = java.sql.DriverManager.getConnection(url, user, Password);
            // Second Method of Update but is not Adding Images
           // String query ="UPDATE `student_info` SET LastName='"+txtLname.getText()+"', MiddleName='"+ txtMname.getText()+"', FirstName='"+txtFname.getText()+"', DOB='"+txtDOB.getText()+"', Status='"+txtStatus.getText()+"', Course='"+txtCourse.getText()+"',Department='"+txtDpt.getText()+"' ,Faculty='"+ txtFac.getText()+"', Program='"+txtPrgm.getText()+"',Level='"+txtLevel.getText()+"', Phone='"+txtPhone.getText()+"', Email='"+txtMail.getText()+"', Address='"+txtAdd.getText()+"', Path='"+txtPath.getText()+"', Photo='"+lblImg.getIcon()+"' WHERE Id="+txtId.getText();
           String query = "UPDATE `student_info` SET LastName=?, MiddleName=?, FirstName=?, DOB=?, Status=?, Course=?, Department=?, Faculty=?, Program=?, Level=?, Phone=?, Email=?, Address=?, Path=?, Photo=? WHERE Id=?";
            pst = conn.prepareStatement(query);
            pst.setString(16, txtId.getText());
            pst.setString(1, txtLname.getText());
            pst.setString(2, txtMname.getText());
            pst.setString(3, txtFname.getText());
            pst.setString(4, txtDOB.getText());
            pst.setString(5, txtStatus.getText());
            pst.setString(6, txtCourse.getText());
            pst.setString(7, txtDpt.getText());
            pst.setString(8, txtFac.getText());
            pst.setString(9, txtPrgm.getText());
            pst.setString(10, txtLevel.getText());
            pst.setString(11, txtPhone.getText());
            pst.setString(12, txtMail.getText());
            pst.setString(13, txtAdd.getText());
            pst.setString(14, txtPath.getText());
            pst.setBytes(15, Photo);
            pst.executeUpdate();
            
            pst = conn.prepareStatement(query);
             pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Updated Successfully");

    }                                         
catch (HeadlessException | SQLException ex1) {
            JOptionPane.showMessageDialog(null, ex1);
        }
       
         showTableData();
            /**
            pst.setString(15, txtId.getText());
            pst.setString(1, txtLname.getText());
            pst.setString(2, txtMname.getText());
            pst.setString(3, txtFname.getText());
            pst.setString(4, txtDOB.getText());
            pst.setString(5, txtStatus.getText());
            pst.setString(6, txtCourse.getText());
            pst.setString(7, txtDpt.getText());
            pst.setString(8, txtFac.getText());
            pst.setString(9, txtPrgm.getText());
            pst.setString(10, txtLevel.getText());
            pst.setString(11, txtPhone.getText());
            pst.setString(12, txtMail.getText());
            pst.setString(13, txtAdd.getText());
            pst.setString(14, txtAdd.getText());
            **/
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
      this.dispose();
       new MenuForm().setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    private void PhotoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoFunActionPerformed
           PhotoFunction f = new PhotoFunction();
        ResultSet rs = null;
        //PreparedStatement pst = null;
        String Id = "Id";
        String fn = "FirstName";
        String ln = "LastName";
        String mn = "MiddleName";
        String cs = "Course";
        String dp = "Depatment";
        String lv = "Level";
        String pg = "Program";
        String pn = "Phone";
        String m = "mail";
        String a = "Address";
        String db = "DOB";
        String pt = "Path";
        String st = "Status";
        String fc = "Faculty";
        String ph = "Photo";
        

       
        rs = f.find(txtPath.getText());
        //rs = f.find(txtSearch.getText());
        try {
              byte[] imageByte;
                Image image;

            if (rs.next()) {
                txtId.setText(rs.getString("Id"));
                txtLname.setText(rs.getString("LastName"));
                txtMname.setText(rs.getString("MiddleName"));
                txtFname.setText(rs.getString("FirstName"));
                txtDOB.setText(rs.getString("DOB"));
                txtLevel.setText(rs.getString("Level"));
                txtPhone.setText(rs.getString("Phone"));
                txtMail.setText(rs.getString("Email"));
                txtStatus.setText(rs.getString("Status"));
                txtCourse.setText(rs.getString("Course"));
                txtDpt.setText(rs.getString("Department"));
                txtFac.setText(rs.getString("Faculty"));
                txtPrgm.setText(rs.getString("Program"));
                txtAdd.setText(rs.getString("Address"));
                txtPath.setText(rs.getString("Path"));
               // pst.setBytes(12, Photo);
                
                imageByte = rs.getBytes("Photo");
                image =getToolkit().createImage(imageByte);
                ImageIcon icon = new ImageIcon(image);
                lblImg.setIcon(icon);
         
    /*           
       File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        //ImageIcon icon = new ImageIcon(filename);
        txtImg.setText(rs.getString("Image"));
         txtImg.setText(filename);
              if(txtImg.setText==filename)
                      {
                           lblImg.setIcon(icon);
                      }
              else{
                  JOptionPane.showMessageDialog(null, "NO DATA FOUND");
              }
                     //File f = chooser.getSelectedFile();
        
       
         String filename = f.getAbsolutePath();
        txtImg.setText(filename);
        Image getAbsoluthPath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(icon);
        txtImg.setText(filename);
        
                  String filename = null;
                 //txtImg.setText(filename);
                  Image getAbsoluthPath = null;
                 byte [] img = rs.getBytes("Images");
                Icon filename;
                 ImageIcon img1 = new ImageIcon((Image) filename);
                 Image im1 = img.getImage(filename);
                 Image myImage;
                myImage = img1.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
                 ImageIcon Image= new ImageIcon(myImage);
                 lblImg.setIcon(filename);
                  */ 
       
       
       
                //ImageIcon icon = new ImageIcon(filename);
            } else {
                JOptionPane.showMessageDialog(null, "NO DATA FOUND! \nInput Another Photo and try Again! ");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_PhotoFunActionPerformed
    
     public class PhotoFunction {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        public ResultSet find(String s) {
            try {
                conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/criminaldetection", "root", "");
                pst = conn.prepareStatement("SELECT * FROM `student_info` WHERE Path = ?");
                pst.setString(1, s);
                rs = pst.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
        }
     }
    
      
        
         /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Student_Info().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Student_Info.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JButton PhotoFun;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTextArea txtAdd;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDpt;
    private javax.swing.JTextField txtFac;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrgm;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
byte[] Photo = null;
String filename = null;
}
